"""created priority, created_at, updated_at fields

Revision ID: 757c5eeb78ef
Revises: d0b8dedae7fc
Create Date: 2025-09-12 19:11:54.663642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757c5eeb78ef'
down_revision: Union[str, Sequence[str], None] = 'd0b8dedae7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
